### ISSUE TITLE
Register for Api Key

### ISSUE THREAD

**Issue by BaileyMillerSSI** [BaileyMillerSSI/Destiny2Api#2]
I know the process is going to be pretty easy but I am not sure how I am going to keep the key private, while still within the public domain.

**Comment by kevinboss** [comment]
Why don't you allow the consumer of the library to set their own key?

**Comment by kevinboss** [comment]
I may have misunderstood the issue. The library seems to expect the key as a string anyway.

**Comment by BaileyMillerSSI** [comment]
This was a reminder to myself to get a key and somehow get it in the code for testing. I have a way right now that is documented. View the homepage, this issue can actually be closed now.
